name: Build and Deploy Ktor Server

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # 3. Делаем fatJar
      - name: Build fat JAR
        run: ./gradlew buildFatJar

      # 4. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Сборка образа
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/ktor-letterpet:latest \
            .

      # 6. Публикация образа
      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ktor-letterpet:latest
